global using System;
global using Shares.Enums;
global using Infrastructures.Databases;
global using Microsoft.AspNetCore.Mvc;
global using Shares.Models.ApiModels;
global using Interfaces.Features.Base;
global using Shares.Models.Paginations;
global using Shares.Extensions;
global using Microsoft.EntityFrameworkCore;
